version: '3'

services:
  # Application
  socket-api:
    build:
      context: .
      target: development
    ports:
      - 3333:3333
    command: npm run start:dev
    networks:
      - nestjs-redis-websocket-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - nestjs-redis-websocket-network

networks:
  nestjs-redis-websocket-network:
    driver: bridge