version: '3'

services:
  # Application
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - nestjs-redis-websocket-network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  pgadmin:
    driver: local

networks:
  nestjs-redis-websocket-network:
    driver: bridge